const fs=require('fs'),path=require('path');
const out=path.join(__dirname,'dist');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
function replaceOne(s,a,b,label){if(!s.includes(a))throw new Error('Trecho não encontrado: '+label);return s.replace(a,b)}
function injectStyle(html,css){return html.replace('</head>',`<style>${css}</style></head>`)}

let index=fs.readFileSync('index.html','utf8');
index=replaceOne(index,'.bars{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:8px 0}','.bars{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin:8px 0}','bars desktop');
index=replaceOne(index,'.bars{grid-template-columns:repeat(3,1fr)}}','.bars{grid-template-columns:repeat(2,1fr)}}','bars mobile');
index=replaceOne(index,"function summary(ch){const s=ch.sheet||{},a=s.attrs||{},L=Number(s.char?.level??ch.level??1),m={pv:Math.max(0,(Number(a.CON)||0)*3+L),ps:Math.max(0,(Number(a.ESP)||0)+(Number(a.INT)||0)+L),pd:Math.max(0,(Number(a.CON)||0)+(Number(a.ESP)||0)+L)};const r=s.resources||{};return{level:L,pv:r.pv??m.pv,pvMax:m.pv,ps:r.ps??m.ps,psMax:m.ps,pd:r.pd??m.pd,pdMax:m.pd,def:(Number(a.DES)||0)+(Number(a.PER)||0)+(Number(a.CON)||0)+(Number(s.char?.armor)||0)}}","function summary(ch){const s=ch.sheet||{},a=s.attrs||{},L=Number(s.char?.level??ch.level??1),per=Number(a.PER)||0,m={pv:Math.max(0,(Number(a.CON)||0)*3+L),ps:Math.max(0,(Number(a.ESP)||0)+(Number(a.INT)||0)+L),pd:Math.max(0,(Number(a.CON)||0)+(Number(a.ESP)||0)+L)};const r=s.resources||{},ca=(Number(a.DES)||0)+per+(Number(a.CON)||0)+(Number(s.char?.armor)||0),cs=(s.char?.alert?per*2:per)+L;return{level:L,pv:r.pv??m.pv,pvMax:m.pv,ps:r.ps??m.ps,psMax:m.ps,pd:r.pd??m.pd,pdMax:m.pd,ca,cs}}",'summary');
index=replaceOne(index,'<div class="bars"><div class="mini-stat"><b>${s.level}</b>NV</div><div class="mini-stat"><b>${s.pv}/${s.pvMax}</b>PV</div><div class="mini-stat"><b>${s.def}</b>DEF</div></div>','<div class="bars"><div class="mini-stat"><b>${s.level}</b>NV</div><div class="mini-stat"><b>${s.pv}/${s.pvMax}</b>PV</div><div class="mini-stat"><b>${s.ca}</b>CA</div><div class="mini-stat"><b>${s.cs}</b>CS</div></div>','cards');
index=replaceOne(index,"char:{name,player,concept:'',level:1,armor:0,pa:0,pressure:0,inventory:'',notes:'',luckNumber:'',otherResources:''}","char:{name,player,concept:'',level:1,armor:0,alert:false,pa:0,pressure:0,inventory:'',notes:'',luckNumber:'',otherResources:''}",'default sheet');
index=index.replace(`<div class="meta"><span class="badge">${kind==='player'?'Jogador':kind==='npc'?'NPC':'Monstro'}</span>${ch.is_in_scene?'<span class="badge live">Em cena</span>':''}</div>`,`<div class="meta"><span class="badge">${kind==='player'?'Jogador':kind==='npc'?'NPC':'Monstro'}</span>${ch.is_in_scene?'<span class="badge live">Em cena</span>':''}${ch.sheet?.char?.alert?'<span class="badge">Alerta</span>':''}</div>`);
index=injectStyle(index,`
.panel{margin-top:18px;padding:20px}.tabs{gap:8px;margin:16px 0}.folder-row{gap:8px;padding:8px}
.entity-grid{grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:12px}.entity{border-radius:14px;padding:14px}.entity h3{margin:6px 0 4px;line-height:1.15}
.bars{grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:10px 0}.mini-stat{border-radius:9px;padding:7px 5px;font-size:10.5px;line-height:1.2}.mini-stat b{font-size:15px;line-height:1.15;margin-bottom:2px}.entity-actions{gap:7px;margin-top:11px}
@media(max-width:1100px){.entity-grid{grid-template-columns:repeat(auto-fill,minmax(240px,1fr))}.bars{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:760px){.panel{padding:14px}.bars{grid-template-columns:repeat(2,minmax(0,1fr))}}
`);
fs.writeFileSync(path.join(out,'index.html'),index);

let sheet=fs.readFileSync('sheet.html','utf8');
sheet=replaceOne(sheet,'.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}','.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}','sheet grid');
sheet=replaceOne(sheet,'<div class="stats" style="margin-top:10px"><div class="stat"><small>Defesa</small><div id="def" class="v"></div></div><div class="stat"><small>PA máximo</small><div id="pamax" class="v"></div></div><div class="stat"><small>PA atual</small><input id="pa" type="number" min="0"></div><div class="stat"><small>Armadura</small><input id="armor" type="number" min="0"></div><div class="stat"><small>Pressão</small><select id="pressure"><option>0</option><option>1</option><option>2</option><option>3</option></select></div><div class="stat"><small>Pts extras negativos</small><div id="neg" class="v"></div></div></div>','<div class="stats" style="margin-top:10px"><div class="stat"><small>CA</small><div id="def" class="v"></div></div><div class="stat"><small>CS</small><div id="senses" class="v"></div><label class="alert-toggle"><input id="alert" type="checkbox"> Em alerta</label></div><div class="stat"><small>PA máximo</small><div id="pamax" class="v"></div></div><div class="stat"><small>PA atual</small><input id="pa" type="number" min="0"></div><div class="stat"><small>Armadura</small><input id="armor" type="number" min="0"></div><div class="stat"><small>Pressão</small><select id="pressure"><option>0</option><option>1</option><option>2</option><option>3</option></select></div><div class="stat"><small>Pts extras negativos</small><div id="neg" class="v"></div></div></div><div class="note" style="margin-top:9px"><b>Classe de Sentidos (CS):</b> é a DT que inimigos precisam superar para evitar ser detectados por você. Normalmente, CS = PER + NP. Ao declarar que está em alerta, CS = (PER × 2) + NP.</div>','sheet stats');
sheet=replaceOne(sheet,'Subir de nível custa <b>10 + NP atual</b>. O mesmo PA usado para níveis também pode ser gasto em perícias e vantagens.','O custo para subir de nível é igual ao valor total da <b>Barra de PA</b>: <b>10 + NP atual</b>. O mesmo PA também pode ser gasto em perícias e vantagens.','level note');
sheet=replaceOne(sheet,'<script src="/sheet-data.js"></script><script src="/sheet-app.js"></script>','<script src="/sheet-data.js"></script><script src="/sheet-app.js"></script><script src="/sheet-extra.js"></script>','extra script');
sheet=injectStyle(sheet,`
.paper{margin-top:14px;padding:18px}.paper h2{margin-bottom:14px;line-height:1.15}.grid{gap:12px}.field{gap:6px}input,select,textarea{padding:9px 10px}.attr{padding:10px 8px}
.stats{grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:10px}.stat{padding:10px 11px;min-height:82px}.note{line-height:1.45;padding:10px 11px}.budget{margin-top:11px;padding:10px 11px}.resource{padding:11px}
.skillgroup,.advattr{margin-top:16px}.skillrow{gap:9px;padding:10px 8px}.modrow{gap:9px;margin:9px 0}.advgrid{gap:12px}.advgroup h3{padding:10px}.advitem{padding:10px}.mastery{padding:10px}.bond{gap:9px;margin:9px 0}
.alert-toggle{display:flex;gap:6px;align-items:center;margin-top:6px;font-size:11px;white-space:nowrap}.alert-toggle input{width:auto;margin:0}
@media(max-width:800px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:520px){.g2,.g3,.g4{grid-template-columns:1fr}.g7,.stats{grid-template-columns:repeat(2,minmax(0,1fr))}.paper{padding:12px}}
`);
fs.writeFileSync(path.join(out,'sheet.html'),sheet);
for(const f of ['sheet-app.js','sheet-data.js'])fs.copyFileSync(f,path.join(out,f));
fs.writeFileSync(path.join(out,'sheet-extra.js'),`const _renderStatsBase=renderStats;\nrenderStats=function(){_renderStatsBase();if(s.char.alert==null)s.char.alert=false;const L=+s.char.level||1,per=+s.attrs.PER||0,cs=(s.char.alert?per*2:per)+L,out=document.querySelector('#senses'),alert=document.querySelector('#alert');if(out)out.textContent=cs;if(alert&&document.activeElement!==alert)alert.checked=!!s.char.alert;};\nconst alertBox=document.querySelector('#alert');if(alertBox)alertBox.onchange=e=>{s.char.alert=!!e.target.checked;save();renderStats();};\n`);
console.log('Quimera build concluído em dist/');
