const fs=require('fs'),path=require('path'),vm=require('vm');
const out=path.join(__dirname,'dist');
const htmlPath=path.join(out,'sheet.html');
let html=fs.readFileSync(htmlPath,'utf8');

const preload=String.raw`(() => {
  const REF='zdhztatcmxxpehbqhvat', STORAGE='sb-'+REF+'-auth-token';
  const status=(text,bad=false)=>{const e=document.querySelector('#sync');if(!e)return;e.textContent=text;e.classList.toggle('bad',bad);e.classList.toggle('ok',!bad)};
  function session(){try{const raw=localStorage.getItem(STORAGE);if(!raw)return null;const x=JSON.parse(raw);return x?.currentSession||x?.session||x||null}catch{return null}}
  window.addEventListener('error',e=>{status('Erro ao carregar',true);console.error('[Quimera]',e.error||e.message)});
  window.addEventListener('unhandledrejection',e=>{status('Erro de conexão',true);console.error('[Quimera]',e.reason)});
  const original=window.supabase?.createClient?.bind(window.supabase);
  if(original){window.supabase.createClient=(url,key,options)=>{
    const client=original(url,key,options),originalGet=client.auth.getSession.bind(client.auth),originalFrom=client.from.bind(client);
    client.auth.getSession=async()=>{const s=session();if(s?.access_token)return {data:{session:s},error:null};return Promise.race([originalGet(),new Promise(r=>setTimeout(()=>r({data:{session:null},error:new Error('Tempo limite da sessão')}),4500))])};
    client.from=(table)=>{
      if(table!=='characters'||!session()?.access_token)return originalFrom(table);
      let mode='select',payload=null,filters={},one=false,cols='*',done=null;
      const exec=async()=>{if(done)return done;done=(async()=>{const s=session();if(!s?.access_token)return {data:null,error:{message:'Sessão não encontrada. Volte à campanha e entre novamente.'}};const qs=new URLSearchParams();if(mode==='select')qs.set('select',cols);Object.entries(filters).forEach(([k,v])=>qs.set(k,'eq.'+v));const headers={apikey:key,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'};if(mode==='update')headers.Prefer='return=minimal';try{const r=await fetch(url+'/rest/v1/characters?'+qs.toString(),{method:mode==='update'?'PATCH':'GET',headers,body:mode==='update'?JSON.stringify(payload):undefined,cache:'no-store'});if(!r.ok){let j={};try{j=await r.json()}catch{};return {data:null,error:{message:j.message||('Erro '+r.status+' ao acessar a ficha.')}}}if(mode==='update')return {data:null,error:null};const data=await r.json();return {data:one?(data[0]||null):data,error:one&&!data[0]?{message:'Ficha não encontrada ou sem permissão.'}:null}}catch(e){return {data:null,error:{message:e?.message||'Falha de rede ao acessar a ficha.'}}}})();return done};
      const chain={select(c='*'){mode='select';cols=c;return chain},update(v){mode='update';payload=v;return chain},eq(k,v){filters[k]=v;return chain},single(){one=true;return exec()},then(ok,fail){return exec().then(ok,fail)}};return chain;
    };
    window.QuimeraRuntime={url,key,client,session,status};return client;
  }}
  const tabs=document.querySelector('header .tabs');if(tabs&&!document.querySelector('[data-tab="initiative"]')){const b=document.createElement('button');b.className='tab';b.dataset.tab='initiative';b.textContent='Iniciativa';tabs.appendChild(b)}
  const main=document.querySelector('main');if(main&&!document.querySelector('#initiative')){const s=document.createElement('section');s.id='initiative';s.className='panel';s.innerHTML='<div class="paper"><h2>Iniciativa</h2><div id="sheetInitiative"><div class="muted">Carregando iniciativa...</div></div></div>';main.appendChild(s)}
})();`;

const initiative=String.raw`(() => {
  let campaign=null,isMaster=false,participants=[],started=false;
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function rest(table,{method='GET',query={},body}={}){const rt=window.QuimeraRuntime,s=rt?.session();if(!rt||!s?.access_token)throw new Error('Sessão não encontrada.');const qs=new URLSearchParams();Object.entries(query).forEach(([k,v])=>qs.set(k,v));const headers={apikey:rt.key,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'};if(method==='PATCH')headers.Prefer='return=representation';const r=await fetch(rt.url+'/rest/v1/'+table+(qs.toString()?'?'+qs.toString():''),{method,headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});if(!r.ok){let j={};try{j=await r.json()}catch{};throw new Error(j.message||('Erro '+r.status))}return r.status===204?null:r.json()}
  const items=()=>Array.isArray(campaign?.initiative)?campaign.initiative:[];
  const sorted=()=>[...items()].sort((a,b)=>(Number(b.value)||0)-(Number(a.value)||0)||String(a.name||'').localeCompare(String(b.name||''),'pt-BR'));
  const kind=k=>k==='player'?'Jogador':k==='npc'?'NPC':k==='monster'?'Monstro':'Outro';
  function render(){const root=$('#sheetInitiative');if(!root)return;const list=sorted();root.innerHTML='<div class="initiative-sheet-head"><div class="muted">Ordem pelo resultado do teste, do maior para o menor.</div>'+(isMaster?'<div class="actions"><button id="sheetInitAdd" class="primary">+ Adicionar</button><button id="sheetInitClear" class="danger">Limpar</button></div>':'<span class="pill">somente o mestre edita</span>')+'</div><div class="initiative-sheet-list">'+(list.length?list.map((it,i)=>'<div class="initiative-sheet-row"><b class="initiative-pos">'+(i+1)+'</b><div><strong>'+esc(it.name||'Sem nome')+'</strong><small>'+esc(kind(it.kind))+'</small></div>'+(isMaster?'<input data-init-value="'+esc(it.id)+'" type="number" value="'+(Number(it.value)||0)+'">':'<b class="initiative-value">'+(Number(it.value)||0)+'</b>')+(isMaster?'<button class="danger" data-init-del="'+esc(it.id)+'">×</button>':'')+'</div>').join(''):'<div class="note">A iniciativa ainda não foi preenchida.</div>')+'</div>';if(!isMaster)return;$('#sheetInitAdd').onclick=openAdd;$('#sheetInitClear').onclick=()=>{if(items().length&&confirm('Limpar toda a iniciativa?'))save([])};root.querySelectorAll('[data-init-value]').forEach(inp=>{inp.onfocus=()=>inp.select();inp.onchange=()=>save(items().map(x=>x.id===inp.dataset.initValue?{...x,value:Number(inp.value)||0}:x))});root.querySelectorAll('[data-init-del]').forEach(b=>{b.onclick=()=>save(items().filter(x=>x.id!==b.dataset.initDel))})}
  async function save(next){campaign.initiative=next;render();try{const rows=await rest('campaigns',{method:'PATCH',query:{id:'eq.'+campaign.id},body:{initiative:next}});if(rows?.[0])campaign=rows[0]}catch(e){alert(e.message);await loadCampaign();render()}}
  function openAdd(){const root=$('#sheetInitiative'),old=$('#initiativeAddBox');if(old){old.remove();return}const box=document.createElement('div');box.id='initiativeAddBox';box.className='initiative-add-box';box.innerHTML='<div class="field"><label>Participante</label><select id="initiativePerson"><option value="">Outro / nome manual</option>'+participants.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+' — '+esc(kind(c.kind))+'</option>').join('')+'</select></div><div class="field"><label>Nome manual</label><input id="initiativeName" placeholder="Opcional"></div><div class="field"><label>Resultado do teste</label><input id="initiativeRoll" type="number" value="0"></div><button id="initiativeConfirm" class="primary">Adicionar à ordem</button>';root.prepend(box);$('#initiativeConfirm').onclick=()=>{const id=$('#initiativePerson').value,c=participants.find(x=>x.id===id),name=$('#initiativeName').value.trim()||c?.name||'';if(!name)return alert('Escolha um participante ou digite um nome.');const it={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),character_id:id||null,name,kind:c?.kind||'custom',value:Number($('#initiativeRoll').value)||0};save([...items(),it])}}
  async function loadCampaign(){const rows=await rest('campaigns',{query:{id:'eq.'+row.campaign_id,select:'id,name,initiative'}});campaign=rows?.[0]||{id:row.campaign_id,initiative:[]}}
  async function init(){if(started||typeof row==='undefined'||!row)return;started=true;try{const rt=window.QuimeraRuntime,s=rt.session();const [campRows,memberRows,charRows]=await Promise.all([rest('campaigns',{query:{id:'eq.'+row.campaign_id,select:'id,name,initiative'}}),rest('campaign_members',{query:{campaign_id:'eq.'+row.campaign_id,user_id:'eq.'+s.user.id,select:'role'}}),rest('characters',{query:{campaign_id:'eq.'+row.campaign_id,is_archived:'eq.false',select:'id,name,kind'}})]);campaign=campRows?.[0]||{id:row.campaign_id,initiative:[]};isMaster=memberRows?.[0]?.role==='master';participants=charRows||[];render();rt.client.channel('sheet-initiative-'+row.campaign_id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'campaigns',filter:'id=eq.'+row.campaign_id},p=>{if(p.new){campaign={...campaign,...p.new};render()}}).subscribe()}catch(e){const root=$('#sheetInitiative');if(root)root.innerHTML='<div class="note bad">Não foi possível carregar a iniciativa: '+esc(e.message)+'</div>'}}
  let tries=0;const timer=setInterval(()=>{tries++;if(typeof row!=='undefined'&&row){clearInterval(timer);init()}else if(tries>100){clearInterval(timer);const root=$('#sheetInitiative');if(root)root.innerHTML='<div class="note bad">A ficha não terminou de carregar.</div>'}},100);
})();`;

new vm.Script(preload);new vm.Script(initiative);
fs.writeFileSync(path.join(out,'sheet-preload.js'),preload);
fs.writeFileSync(path.join(out,'sheet-initiative.js'),initiative);
const old='<script src="/sheet-data.js"></script><script src="/sheet-app.js"></script><script src="/sheet-extra.js"></script>';
const fresh='<script src="/sheet-data.js?v=10"></script><script src="/sheet-preload.js?v=10"></script><script src="/sheet-app.js?v=10"></script><script src="/sheet-extra.js?v=10"></script>';
if(!html.includes(old))throw new Error('Sequência base de scripts não encontrada em sheet.html');
html=html.replace(old,fresh).replace('<script src="/sheet-master-extra.js"></script>','<script src="/sheet-master-extra.js?v=10"></script>');
if(!html.includes('/sheet-initiative.js'))html=html.replace('</body>','<script src="/sheet-initiative.js?v=10"></script></body>');
html=html.replace('</head>',`<style>.initiative-sheet-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:12px}.initiative-sheet-list{display:grid;gap:8px}.initiative-sheet-row{display:grid;grid-template-columns:36px minmax(0,1fr) 82px auto;gap:9px;align-items:center;padding:9px;border:1px solid var(--line);border-radius:10px;background:#fff9ed99}.initiative-sheet-row strong,.initiative-sheet-row small{display:block}.initiative-sheet-row small{color:#6d6570}.initiative-pos,.initiative-value{color:var(--p);font-size:18px;text-align:center}.initiative-sheet-row input{text-align:center;font-weight:900}.initiative-add-box{display:grid;grid-template-columns:1.4fr 1fr .7fr auto;gap:9px;align-items:end;margin-bottom:12px;padding:10px;border:1px solid var(--line);border-radius:11px;background:#583b8c0c}@media(max-width:700px){.initiative-add-box{grid-template-columns:1fr}.initiative-sheet-row{grid-template-columns:30px minmax(0,1fr) 66px auto}}</style></head>`);
fs.writeFileSync(htmlPath,html);
console.log('runtime fix ok');
