const fs=require('fs'),path=require('path');
const out=path.join(__dirname,'dist');
function addBefore(file,needle,addition){let p=path.join(out,file),s=fs.readFileSync(p,'utf8');if(!s.includes(addition)){if(!s.includes(needle))throw new Error(`Trecho não encontrado em ${file}`);s=s.replace(needle,addition+needle);fs.writeFileSync(p,s)}}

addBefore('index.html','</head>',`<style>
.initiative-panel{margin:14px 0;padding:13px;border:1px solid rgba(88,59,140,.2);border-radius:14px;background:rgba(255,255,255,.34)}
.initiative-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:9px}.initiative-head h3{margin:0;color:var(--purple)}
.initiative-list{display:grid;gap:6px}.init-row{display:grid;grid-template-columns:38px minmax(0,1fr) 82px auto;gap:8px;align-items:center;border:1px solid rgba(88,59,140,.14);border-radius:10px;padding:7px 9px;background:rgba(255,255,255,.45)}
.init-pos{font-size:16px;font-weight:950;color:var(--purple);text-align:center}.init-name{font-weight:900;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.init-kind{font-size:10px;color:var(--muted);font-weight:800}.init-value{font-size:16px;font-weight:950;color:var(--purple);text-align:center}.init-row input{width:76px;border:1px solid var(--line);border-radius:8px;padding:6px;background:rgba(255,255,255,.75);text-align:center;font-weight:900;color:var(--purple)}
@media(max-width:560px){.init-row{grid-template-columns:32px minmax(0,1fr) 68px auto;padding:7px 6px}.init-row input{width:64px}.initiative-panel{padding:10px}}
</style>`);
addBefore('index.html','</body>','<script src="/initiative-extra.js"></script>');

const initiativeExtra=String.raw`
function initiativeItems(){return Array.isArray(currentCampaign?.initiative)?currentCampaign.initiative:[]}
function initiativeEntity(item){return chars.find(c=>c.id===item.character_id)||null}
function initiativeDisplayName(item){return initiativeEntity(item)?.name||item.name||'Sem nome'}
function initiativeKind(item){const c=initiativeEntity(item),k=c?.kind||item.kind;return k==='player'?'Jogador':k==='npc'?'NPC':k==='monster'?'Monstro':'Outro'}
function initiativeSorted(){return [...initiativeItems()].sort((a,b)=>(Number(b.value)||0)-(Number(a.value)||0)||initiativeDisplayName(a).localeCompare(initiativeDisplayName(b),'pt-BR'))}
async function persistInitiative(list){if(!currentCampaign||currentRole!=='master')return;currentCampaign.initiative=list;renderInitiative();const {error}=await sb.from('campaigns').update({initiative:list}).eq('id',currentCampaign.id);if(error){toast(error.message);await loadCampaigns();const fresh=campaigns.find(c=>c.id===currentCampaign.id);if(fresh)currentCampaign=fresh;renderInitiative()}}
function openInitiativeAdd(){const options=chars.map(c=>'<option value="'+c.id+'">'+esc(c.name)+' — '+(c.kind==='player'?'Jogador':c.kind==='npc'?'NPC':'Monstro')+'</option>').join('');showModal('Adicionar à iniciativa','<div class="field"><label>Participante</label><select id="initChar"><option value="">Outro / nome manual</option>'+options+'</select></div><div class="field"><label>Nome manual (opcional)</label><input id="initName" placeholder="Ex.: Armadilha, Horda, Evento"></div><div class="field"><label>Resultado do teste</label><input id="initValue" type="number" value="0"></div><button id="initSave" class="btn primary" style="width:100%">Adicionar</button>');document.querySelector('#initSave').onclick=async()=>{const characterId=document.querySelector('#initChar').value||null,custom=document.querySelector('#initName').value.trim(),c=chars.find(x=>x.id===characterId),name=custom||c?.name||'';if(!name)return toast('Escolha um participante ou digite um nome.');const item={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),character_id:characterId,name,kind:c?.kind||'custom',value:Number(document.querySelector('#initValue').value)||0};closeModal();await persistInitiative([...initiativeItems(),item])}}
function renderInitiative(){if(!currentCampaign)return;const body=document.querySelector('#campaignBody');if(!body)return;let panel=document.querySelector('#initiativePanel');if(!panel){panel=document.createElement('div');panel.id='initiativePanel';panel.className='initiative-panel';body.parentNode.insertBefore(panel,body)}const master=currentRole==='master',items=initiativeSorted();panel.innerHTML='<div class="initiative-head"><div><h3>Iniciativa</h3><div class="muted">Ordem automática pelo resultado do teste: maior primeiro.</div></div>'+(master?'<div class="actions"><button id="initAdd" class="btn primary small">+ Adicionar</button><button id="initClear" class="btn small danger">Limpar</button></div>':'<span class="badge live">visível ao grupo</span>')+'</div><div class="initiative-list">'+(items.length?items.map((it,i)=>'<div class="init-row" data-init="'+esc(it.id)+'"><div class="init-pos">'+(i+1)+'</div><div><div class="init-name">'+esc(initiativeDisplayName(it))+'</div><div class="init-kind">'+esc(initiativeKind(it))+'</div></div>'+(master?'<input data-init-value="'+esc(it.id)+'" type="number" value="'+(Number(it.value)||0)+'">':'<div class="init-value">'+(Number(it.value)||0)+'</div>')+(master?'<button class="btn small danger" data-init-del="'+esc(it.id)+'">×</button>':'<span></span>')+'</div>').join(''):'<div class="empty" style="padding:14px">A iniciativa ainda não foi preenchida.</div>')+'</div>';if(master){document.querySelector('#initAdd').onclick=openInitiativeAdd;document.querySelector('#initClear').onclick=()=>{if(initiativeItems().length&&confirm('Limpar toda a iniciativa?'))persistInitiative([])};panel.querySelectorAll('[data-init-value]').forEach(inp=>{inp.onfocus=()=>inp.select();inp.onchange=()=>{const id=inp.dataset.initValue,list=initiativeItems().map(x=>x.id===id?{...x,value:Number(inp.value)||0}:x);persistInitiative(list)}});panel.querySelectorAll('[data-init-del]').forEach(b=>b.onclick=()=>persistInitiative(initiativeItems().filter(x=>x.id!==b.dataset.initDel)))}}
const _renderCampaignInitiative=renderCampaign;renderCampaign=function(){_renderCampaignInitiative();renderInitiative()};
const _renderCampaignBodyInitiative=renderCampaignBody;renderCampaignBody=function(){_renderCampaignBodyInitiative();renderInitiative()};
subscribeCampaign=function(){if(channel)sb.removeChannel(channel);channel=sb.channel('campaign-'+currentCampaign.id).on('postgres_changes',{event:'*',schema:'public',table:'characters',filter:'campaign_id=eq.'+currentCampaign.id},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'folders',filter:'campaign_id=eq.'+currentCampaign.id},scheduleRefresh).on('postgres_changes',{event:'UPDATE',schema:'public',table:'campaigns',filter:'id=eq.'+currentCampaign.id},p=>{if(p.new){currentCampaign={...currentCampaign,...p.new};renderInitiative()}}).subscribe()};
`;
fs.writeFileSync(path.join(out,'initiative-extra.js'),initiativeExtra);

addBefore('sheet.html','</head>',`<style>
.master-entity-note{margin-top:9px;padding:9px 10px;border-radius:9px;background:#583b8c12;border-left:4px solid var(--p);font-size:12px;line-height:1.4}.skill-level-direct{max-width:68px;text-align:center;padding:6px!important;font-weight:900}
</style>`);
addBefore('sheet.html','</body>','<script src="/sheet-master-extra.js"></script>');

const sheetMasterExtra=String.raw`
function isMasterEntity(){return !!row&&row.kind!=='player'}
const _renderAttrsPlayer=renderAttrs;renderAttrs=function(){if(!isMasterEntity())return _renderAttrsPlayer();let w=document.querySelector('#attrs');w.innerHTML='';Q.attrs.forEach(([c,n])=>{let d=document.createElement('div');d.className='attr';d.innerHTML='<b>'+c+'</b><div class="muted">'+n+'</div><input type="number" min="-5" max="20" value="'+(s.attrs[c]??0)+'">';let inp=d.querySelector('input');inp.onfocus=()=>inp.select();inp.onchange=()=>{s.attrs[c]=Math.max(-5,Math.min(20,Number(inp.value)||0));save();renderAll()};w.appendChild(d)})};
const _renderSkillsPlayer=renderSkills;renderSkills=function(){if(!isMasterEntity())return _renderSkillsPlayer();let w=document.querySelector('#skills');w.innerHTML='';for(let fam of ['Físicas','Mentais','Combate']){let sec=document.createElement('div');sec.className='skillgroup';sec.innerHTML='<h3>'+fam+'</h3>';Q.skills.filter(x=>x[0]===fam).forEach(([_,n,p,ss])=>{let l=Number(s.skills[n])||0,r=document.createElement('div');r.className='skillrow';r.innerHTML='<b>'+n+'</b><span>NV <input class="skill-level-direct" type="number" min="0" max="5" value="'+l+'"></span><span class="die">'+die(eff(l,p,false,n,fam))+(ss?'<small class="muted"> / '+die(eff(l,ss,true,n,fam))+'</small>':'')+'</span><span class="sc muted">SC '+p+(ss?'/'+ss:'')+'</span><span class="pill">livre</span>';let inp=r.querySelector('input');inp.onfocus=()=>inp.select();inp.onchange=()=>{s.skills[n]=Math.max(0,Math.min(5,Number(inp.value)||0));save();renderAll()};sec.appendChild(r)});w.appendChild(sec)}};
const _toggleAdvPlayer=toggleAdv;toggleAdv=function(attr,gi,ai,on){if(!isMasterEntity())return _toggleAdvPlayer(attr,gi,ai,on);const key=attr+':'+gi+':'+ai;if(on){s.advantages[key]=true;if(attr==='SORTE'&&!s.luckSources[key])s.luckSources[key]='PER'}else{delete s.advantages[key];delete s.luckSources[key]}save();renderAll()};
const _renderProgressPlayer=renderProgress;renderProgress=function(){if(!isMasterEntity())return _renderProgressPlayer();const L=Number(s.char.level)||1;document.querySelector('#creationpa').value=s.creation.pa||0;document.querySelector('#creationmode').checked=false;document.querySelector('#creationpa').disabled=true;document.querySelector('#creationmode').disabled=true;document.querySelector('#levelup').disabled=true;document.querySelector('#levelup').textContent='Nível definido pelo mestre';document.querySelector('#levelhint').textContent='NPCs e monstros usam edição livre.'};
const _renderStatsMaster=renderStats;renderStats=function(){_renderStatsMaster();if(!isMasterEntity())return;const level=document.querySelector('#level');level.removeAttribute('readonly');level.min=1;level.max=20;level.type='number';level.onfocus=()=>level.select();level.onchange=()=>{s.char.level=Math.max(1,Math.min(20,Number(level.value)||1));save();renderAll()};const b=document.querySelector('#budget');b.classList.remove('over');b.innerHTML='<b>Edição livre do mestre.</b> NPCs e monstros não precisam obedecer ao orçamento de atributos ou gastar PA para definir perícias e vantagens.';let note=document.querySelector('#masterEntityNote');if(!note){note=document.createElement('div');note.id='masterEntityNote';note.className='master-entity-note';document.querySelector('#budget').insertAdjacentElement('afterend',note)}note.innerHTML='<b>'+((row.kind==='npc')?'NPC':'Monstro')+':</b> ajuste nível, atributos, perícias, recursos e demais campos diretamente.'};
`;
fs.writeFileSync(path.join(out,'sheet-master-extra.js'),sheetMasterExtra);
console.log('Quimera postbuild concluído: iniciativa + edição de NPC/monstro');
