const fs=require('fs'),path=require('path');
const out=path.join(__dirname,'dist');
function addBefore(file,needle,addition){let p=path.join(out,file),s=fs.readFileSync(p,'utf8');if(!s.includes(addition)){if(!s.includes(needle))throw new Error(`Trecho não encontrado em ${file}`);s=s.replace(needle,addition+needle);fs.writeFileSync(p,s)}}
function replaceIn(file,a,b,label){let p=path.join(out,file),s=fs.readFileSync(p,'utf8');if(!s.includes(a))throw new Error(`Trecho não encontrado em ${file}: ${label}`);s=s.replace(a,b);fs.writeFileSync(p,s)}

// ---------------- Dashboard / campaign initiative ----------------
addBefore('index.html','</head>',`<style>
.initiative-panel{margin:14px 0;padding:13px;border:1px solid rgba(88,59,140,.2);border-radius:14px;background:rgba(255,255,255,.34)}
.initiative-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:9px}.initiative-head h3{margin:0;color:var(--purple)}
.initiative-list{display:grid;gap:6px}.init-row{display:grid;grid-template-columns:38px minmax(0,1fr) 82px auto;gap:8px;align-items:center;border:1px solid rgba(88,59,140,.14);border-radius:10px;padding:7px 9px;background:rgba(255,255,255,.45)}
.init-pos{font-size:16px;font-weight:950;color:var(--purple);text-align:center}.init-name{font-weight:900;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.init-kind{font-size:10px;color:var(--muted);font-weight:800}.init-value{font-size:16px;font-weight:950;color:var(--purple);text-align:center}.init-row input{width:76px;border:1px solid var(--line);border-radius:8px;padding:6px;background:rgba(255,255,255,.75);text-align:center;font-weight:900;color:var(--purple)}
@media(max-width:560px){.init-row{grid-template-columns:32px minmax(0,1fr) 68px auto;padding:7px 6px}.init-row input{width:64px}.initiative-panel{padding:10px}}
</style>`);
addBefore('index.html','</body>','<script src="/initiative-extra.js?v=7"></script>');

const initiativeExtra=String.raw`
function initiativeItems(){return Array.isArray(currentCampaign?.initiative)?currentCampaign.initiative:[]}
function initiativeEntity(item){return chars.find(c=>c.id===item.character_id)||null}
function initiativeDisplayName(item){return initiativeEntity(item)?.name||item.name||'Sem nome'}
function initiativeKind(item){const c=initiativeEntity(item),k=c?.kind||item.kind;return k==='player'?'Jogador':k==='npc'?'NPC':k==='monster'?'Monstro':'Outro'}
function initiativeSorted(){return [...initiativeItems()].sort((a,b)=>(Number(b.value)||0)-(Number(a.value)||0)||initiativeDisplayName(a).localeCompare(initiativeDisplayName(b),'pt-BR'))}
async function persistInitiative(list){if(!currentCampaign||currentRole!=='master')return;currentCampaign.initiative=list;renderInitiative();const {error}=await sb.from('campaigns').update({initiative:list}).eq('id',currentCampaign.id);if(error){toast(error.message);await loadCampaigns();const fresh=campaigns.find(c=>c.id===currentCampaign.id);if(fresh)currentCampaign=fresh;renderInitiative()}}
function openInitiativeAdd(){const options=chars.map(c=>'<option value="'+c.id+'">'+esc(c.name)+' — '+(c.kind==='player'?'Jogador':c.kind==='npc'?'NPC':'Monstro')+'</option>').join('');showModal('Adicionar à iniciativa','<div class="field"><label>Participante</label><select id="initChar"><option value="">Outro / nome manual</option>'+options+'</select></div><div class="field"><label>Nome manual (opcional)</label><input id="initName" placeholder="Ex.: Armadilha, Horda, Evento"></div><div class="field"><label>Resultado do teste</label><input id="initValue" type="number" value="0"></div><button id="initSave" class="btn primary" style="width:100%">Adicionar</button>');document.querySelector('#initSave').onclick=async()=>{const characterId=document.querySelector('#initChar').value||null,custom=document.querySelector('#initName').value.trim(),c=chars.find(x=>x.id===characterId),name=custom||c?.name||'';if(!name)return toast('Escolha um participante ou digite um nome.');const item={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),character_id:characterId,name,kind:c?.kind||'custom',value:Number(document.querySelector('#initValue').value)||0};closeModal();await persistInitiative([...initiativeItems(),item])}}
function renderInitiative(){if(!currentCampaign)return;const body=document.querySelector('#campaignBody');if(!body)return;let panel=document.querySelector('#initiativePanel');if(!panel){panel=document.createElement('div');panel.id='initiativePanel';panel.className='initiative-panel';body.parentNode.insertBefore(panel,body)}const master=currentRole==='master',items=initiativeSorted();panel.innerHTML='<div class="initiative-head"><div><h3>Iniciativa</h3><div class="muted">Ordem automática pelo resultado do teste: maior primeiro.</div></div>'+(master?'<div class="actions"><button id="initAdd" class="btn primary small">+ Adicionar</button><button id="initClear" class="btn small danger">Limpar</button></div>':'<span class="badge live">visível ao grupo</span>')+'</div><div class="initiative-list">'+(items.length?items.map((it,i)=>'<div class="init-row" data-init="'+esc(it.id)+'"><div class="init-pos">'+(i+1)+'</div><div><div class="init-name">'+esc(initiativeDisplayName(it))+'</div><div class="init-kind">'+esc(initiativeKind(it))+'</div></div>'+(master?'<input data-init-value="'+esc(it.id)+'" type="number" value="'+(Number(it.value)||0)+'">':'<div class="init-value">'+(Number(it.value)||0)+'</div>')+(master?'<button class="btn small danger" data-init-del="'+esc(it.id)+'">×</button>':'<span></span>')+'</div>').join(''):'<div class="empty" style="padding:14px">A iniciativa ainda não foi preenchida.</div>')+'</div>';if(master){document.querySelector('#initAdd').onclick=openInitiativeAdd;document.querySelector('#initClear').onclick=()=>{if(initiativeItems().length&&confirm('Limpar toda a iniciativa?'))persistInitiative([])};panel.querySelectorAll('[data-init-value]').forEach(inp=>{inp.onfocus=()=>inp.select();inp.onchange=()=>{const id=inp.dataset.initValue,list=initiativeItems().map(x=>x.id===id?{...x,value:Number(inp.value)||0}:x);persistInitiative(list)}});panel.querySelectorAll('[data-init-del]').forEach(b=>b.onclick=()=>persistInitiative(initiativeItems().filter(x=>x.id!==b.dataset.initDel)))}}
const _renderCampaignInitiative=renderCampaign;renderCampaign=function(){_renderCampaignInitiative();renderInitiative()};
const _renderCampaignBodyInitiative=renderCampaignBody;renderCampaignBody=function(){_renderCampaignBodyInitiative();renderInitiative()};
subscribeCampaign=function(){if(channel)sb.removeChannel(channel);channel=sb.channel('campaign-'+currentCampaign.id).on('postgres_changes',{event:'*',schema:'public',table:'characters',filter:'campaign_id=eq.'+currentCampaign.id},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'folders',filter:'campaign_id=eq.'+currentCampaign.id},scheduleRefresh).on('postgres_changes',{event:'UPDATE',schema:'public',table:'campaigns',filter:'id=eq.'+currentCampaign.id},p=>{if(p.new){currentCampaign={...currentCampaign,...p.new};renderInitiative()}}).subscribe()};
`;
fs.writeFileSync(path.join(out,'initiative-extra.js'),initiativeExtra);

// ---------------- Sheet: free master edit + initiative tab ----------------
replaceIn('sheet.html','<script src="/sheet-data.js"></script><script src="/sheet-app.js"></script><script src="/sheet-extra.js"></script>','<script src="/sheet-data.js?v=7"></script><script src="/sheet-app.js?v=7"></script><script src="/sheet-extra.js?v=7"></script>','sheet script versions');
replaceIn('sheet.html','<button class="tab" data-tab="notas">Laços & Notas</button>','<button class="tab" data-tab="notas">Laços & Notas</button><button class="tab" data-tab="initiative">Iniciativa</button>','initiative tab');
addBefore('sheet.html','</main>',`<section id="initiative" class="panel"><div class="paper"><div class="initiative-sheet-head"><div><h2>Iniciativa</h2><div class="muted">A ordem é compartilhada com toda a campanha. Apenas o mestre pode editar.</div></div><span id="initiativeRole" class="pill">Carregando...</span></div><div id="initiativeSheetList" class="initiative-sheet-list"><div class="note">Carregando iniciativa...</div></div></div></section>`);
addBefore('sheet.html','</head>',`<style>
.master-entity-note{margin-top:9px;padding:9px 10px;border-radius:9px;background:#583b8c12;border-left:4px solid var(--p);font-size:12px;line-height:1.4}.skill-level-direct{max-width:68px;text-align:center;padding:6px!important;font-weight:900}
.initiative-sheet-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;flex-wrap:wrap}.initiative-sheet-list{display:grid;gap:8px;margin-top:12px}.initiative-sheet-row{display:grid;grid-template-columns:38px minmax(0,1fr) 78px auto;gap:8px;align-items:center;border:1px solid var(--line);border-radius:11px;padding:9px;background:#fff9ed99}.initiative-sheet-pos{text-align:center;font-weight:950;color:var(--p);font-size:17px}.initiative-sheet-name{font-weight:900}.initiative-sheet-kind{font-size:10px;color:#6d6570}.initiative-sheet-value{font-weight:950;color:var(--p);text-align:center;font-size:17px}.initiative-sheet-row input{padding:7px;text-align:center;font-weight:900}.initiative-sheet-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}
@media(max-width:520px){.initiative-sheet-row{grid-template-columns:30px minmax(0,1fr) 62px auto;padding:8px 6px}.initiative-sheet-row input{padding:6px}}
</style>`);
addBefore('sheet.html','</body>','<script src="/sheet-master-extra.js?v=7"></script><script src="/sheet-initiative-extra.js?v=7"></script>');

const sheetMasterExtra=String.raw`
function isMasterEntity(){return !!row&&row.kind!=='player'}
const _renderAttrsPlayer=renderAttrs;renderAttrs=function(){if(!isMasterEntity())return _renderAttrsPlayer();let w=document.querySelector('#attrs');w.innerHTML='';Q.attrs.forEach(([c,n])=>{let d=document.createElement('div');d.className='attr';d.innerHTML='<b>'+c+'</b><div class="muted">'+n+'</div><input type="number" min="-5" max="20" value="'+(s.attrs[c]??0)+'">';let inp=d.querySelector('input');inp.onfocus=()=>inp.select();inp.onchange=()=>{s.attrs[c]=Math.max(-5,Math.min(20,Number(inp.value)||0));save();renderAll()};w.appendChild(d)})};
const _renderSkillsPlayer=renderSkills;renderSkills=function(){if(!isMasterEntity())return _renderSkillsPlayer();let w=document.querySelector('#skills');w.innerHTML='';for(let fam of ['Físicas','Mentais','Combate']){let sec=document.createElement('div');sec.className='skillgroup';sec.innerHTML='<h3>'+fam+'</h3>';Q.skills.filter(x=>x[0]===fam).forEach(([_,n,p,ss])=>{let l=Number(s.skills[n])||0,r=document.createElement('div');r.className='skillrow';r.innerHTML='<b>'+n+'</b><span>NV <input class="skill-level-direct" type="number" min="0" max="5" value="'+l+'"></span><span class="die">'+die(eff(l,p,false,n,fam))+(ss?'<small class="muted"> / '+die(eff(l,ss,true,n,fam))+'</small>':'')+'</span><span class="sc muted">SC '+p+(ss?'/'+ss:'')+'</span><span class="pill">livre</span>';let inp=r.querySelector('input');inp.onfocus=()=>inp.select();inp.onchange=()=>{s.skills[n]=Math.max(0,Math.min(5,Number(inp.value)||0));save();renderAll()};sec.appendChild(r)});w.appendChild(sec)}};
const _toggleAdvPlayer=toggleAdv;toggleAdv=function(attr,gi,ai,on){if(!isMasterEntity())return _toggleAdvPlayer(attr,gi,ai,on);const key=attr+':'+gi+':'+ai;if(on){s.advantages[key]=true;if(attr==='SORTE'&&!s.luckSources[key])s.luckSources[key]='PER'}else{delete s.advantages[key];delete s.luckSources[key]}save();renderAll()};
const _renderProgressPlayer=renderProgress;renderProgress=function(){if(!isMasterEntity())return _renderProgressPlayer();const L=Number(s.char.level)||1;document.querySelector('#creationpa').value=s.creation.pa||0;document.querySelector('#creationmode').checked=false;document.querySelector('#creationpa').disabled=true;document.querySelector('#creationmode').disabled=true;document.querySelector('#levelup').disabled=true;document.querySelector('#levelup').textContent='Nível definido pelo mestre';document.querySelector('#levelhint').textContent='NPCs e monstros usam edição livre.'};
const _renderStatsMaster=renderStats;renderStats=function(){_renderStatsMaster();if(!isMasterEntity())return;const level=document.querySelector('#level');level.removeAttribute('readonly');level.min=1;level.max=20;level.type='number';level.value=Number(s.char.level)||1;level.onfocus=()=>level.select();level.onchange=()=>{s.char.level=Math.max(1,Math.min(20,Number(level.value)||1));save();renderAll()};const b=document.querySelector('#budget');b.classList.remove('over');b.innerHTML='<b>Edição livre do mestre.</b> NPCs e monstros não precisam obedecer ao orçamento de atributos ou gastar PA para definir perícias e vantagens.';let note=document.querySelector('#masterEntityNote');if(!note){note=document.createElement('div');note.id='masterEntityNote';note.className='master-entity-note';document.querySelector('#budget').insertAdjacentElement('afterend',note)}note.innerHTML='<b>'+((row.kind==='npc')?'NPC':'Monstro')+':</b> ajuste nível, atributos, perícias, recursos e demais campos diretamente.'};
`;
fs.writeFileSync(path.join(out,'sheet-master-extra.js'),sheetMasterExtra);

const sheetInitiativeExtra=String.raw`
let sheetCampaign=null,sheetRole=null,sheetInitiativeChannel=null;
function shEsc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function shItems(){return Array.isArray(sheetCampaign?.initiative)?sheetCampaign.initiative:[]}
function shSorted(){return [...shItems()].sort((a,b)=>(Number(b.value)||0)-(Number(a.value)||0)||String(a.name||'').localeCompare(String(b.name||''),'pt-BR'))}
function shKind(k){return k==='player'?'Jogador':k==='npc'?'NPC':k==='monster'?'Monstro':'Outro'}
async function shPersist(list){if(sheetRole!=='master'||!sheetCampaign)return;sheetCampaign.initiative=list;shRender();const {error}=await db.from('campaigns').update({initiative:list}).eq('id',sheetCampaign.id);if(error){toast(error.message);await shLoad()}}
async function shLoad(){if(!row?.campaign_id){const q=await db.from('characters').select('campaign_id').eq('id',ID).single();if(q.error)return;row={...(row||{}),campaign_id:q.data.campaign_id}}const {data:{session}}=await db.auth.getSession();if(!session)return;const [c,m,ch]=await Promise.all([db.from('campaigns').select('id,name,initiative').eq('id',row.campaign_id).single(),db.from('campaign_members').select('role').eq('campaign_id',row.campaign_id).eq('user_id',session.user.id).maybeSingle(),db.from('characters').select('id,name,kind').eq('campaign_id',row.campaign_id)]);if(c.error)return;sheetCampaign=c.data;sheetRole=m.data?.role||'player';window.__sheetInitChars=ch.data||[];shRender();if(sheetInitiativeChannel)db.removeChannel(sheetInitiativeChannel);sheetInitiativeChannel=db.channel('sheet-init-'+row.campaign_id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'campaigns',filter:'id=eq.'+row.campaign_id},p=>{sheetCampaign={...sheetCampaign,...p.new};shRender()}).subscribe()}
function shOpenAdd(){const chars=window.__sheetInitChars||[],opts=chars.map(c=>'<option value="'+c.id+'">'+shEsc(c.name)+' — '+shKind(c.kind)+'</option>').join('');let wrap=document.createElement('div');wrap.className='paper';wrap.style.position='fixed';wrap.style.zIndex='1000';wrap.style.left='50%';wrap.style.top='50%';wrap.style.transform='translate(-50%,-50%)';wrap.style.width='min(92vw,460px)';wrap.style.boxShadow='0 18px 60px #0006';wrap.innerHTML='<h2>Adicionar à iniciativa</h2><div class="field"><label>Participante</label><select id="shInitChar"><option value="">Outro / nome manual</option>'+opts+'</select></div><div class="field"><label>Nome manual</label><input id="shInitName" placeholder="Opcional"></div><div class="field"><label>Resultado do teste</label><input id="shInitValue" type="number" value="0"></div><div class="row" style="margin-top:10px"><button id="shInitSave" class="primary">Adicionar</button><button id="shInitCancel">Cancelar</button></div>';document.body.appendChild(wrap);wrap.querySelector('#shInitCancel').onclick=()=>wrap.remove();wrap.querySelector('#shInitSave').onclick=()=>{const cid=wrap.querySelector('#shInitChar').value||null,c=chars.find(x=>x.id===cid),custom=wrap.querySelector('#shInitName').value.trim(),name=custom||c?.name||'';if(!name)return toast('Escolha um participante ou digite um nome.');const item={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),character_id:cid,name,kind:c?.kind||'custom',value:Number(wrap.querySelector('#shInitValue').value)||0};wrap.remove();shPersist([...shItems(),item])}}
function shRender(){const list=document.querySelector('#initiativeSheetList'),role=document.querySelector('#initiativeRole');if(!list||!role)return;const master=sheetRole==='master',items=shSorted();role.textContent=master?'Mestre · edição liberada':'Jogador · somente leitura';list.innerHTML=(items.length?items.map((it,i)=>'<div class="initiative-sheet-row"><div class="initiative-sheet-pos">'+(i+1)+'</div><div><div class="initiative-sheet-name">'+shEsc(it.name||'Sem nome')+'</div><div class="initiative-sheet-kind">'+shKind(it.kind)+'</div></div>'+(master?'<input data-sh-value="'+shEsc(it.id)+'" type="number" value="'+(Number(it.value)||0)+'">':'<div class="initiative-sheet-value">'+(Number(it.value)||0)+'</div>')+(master?'<button data-sh-del="'+shEsc(it.id)+'" class="danger">×</button>':'<span></span>')+'</div>').join(''):'<div class="note">A iniciativa ainda não foi preenchida.</div>')+(master?'<div class="initiative-sheet-actions"><button id="shAdd" class="primary">+ Adicionar</button><button id="shClear" class="danger">Limpar</button></div>':'');if(master){list.querySelector('#shAdd').onclick=shOpenAdd;list.querySelector('#shClear').onclick=()=>{if(shItems().length&&confirm('Limpar toda a iniciativa?'))shPersist([])};list.querySelectorAll('[data-sh-value]').forEach(inp=>{inp.onfocus=()=>inp.select();inp.onchange=()=>shPersist(shItems().map(x=>x.id===inp.dataset.shValue?{...x,value:Number(inp.value)||0}:x))});list.querySelectorAll('[data-sh-del]').forEach(b=>b.onclick=()=>shPersist(shItems().filter(x=>x.id!==b.dataset.shDel))}}
(async function waitSheet(){for(let i=0;i<40;i++){if(row?.campaign_id){await shLoad();return}await new Promise(r=>setTimeout(r,100))}await shLoad()})();
`;
fs.writeFileSync(path.join(out,'sheet-initiative-extra.js'),sheetInitiativeExtra);

console.log('Quimera postbuild concluído: iniciativa na campanha/ficha + edição livre NPC/monstro');
