const Q={
attrs:[['CON','Constituição'],['FOR','Força'],['DES','Destreza'],['INT','Intelecto'],['PER','Percepção'],['CAR','Carisma'],['ESP','Espírito']],
mastery:{CON:[[4,'Casca Grossa'],[8,'Corpo Resiliente'],[12,'Ritmo Constante'],[16,'Persistência Física']],FOR:[[4,'Pulso Firme'],[8,'Fibrado'],[12,'Bodylifter'],[16,'Muralha']],DES:[[4,'Mãos Ágeis'],[8,'Coordenação Básica'],[12,'Movimento Adaptável'],[16,'Fluidez Natural']],INT:[[4,'CDF'],[8,'Nerdola'],[12,'Analista de Campo'],[16,'Mestre da Gambiarra']],PER:[[4,'Bala na Agulha'],[8,'Atenção Ativa'],[12,'Leitura do Ambiente'],[16,'Sexto Sentido']],CAR:[[4,'Charlatão'],[8,'Boa Pinta'],[12,'Popular'],[16,'Popstar']],ESP:[[4,'Místico'],[8,'Sensitivo'],[12,'Esotérico'],[16,'Transcendente']]},
skills:[
['Físicas','Fortitude','CON'],['Físicas','Movimento','DES'],['Físicas','Postura','CON'],['Físicas','Agilidade','DES'],['Físicas','Potência','FOR'],['Físicas','Visão','PER'],['Físicas','Audição','PER'],['Físicas','Intimidação','CON'],
['Mentais','Investigação','INT'],['Mentais','Ocultismo','INT'],['Mentais','Astúcia','INT'],['Mentais','Atração','CAR'],['Mentais','Observação','PER'],['Mentais','Ciências','INT'],['Mentais','Cuidados','INT'],['Mentais','Pilotar','DES'],['Mentais','Sobrevivência','INT'],['Mentais','Persuasão','CAR'],['Mentais','Inspiração','CAR'],['Mentais','Presença','ESP'],['Mentais','Compostura','ESP'],['Mentais','Linguagens','INT'],
['Combate','Técnica','DES','INT'],['Combate','Briga','FOR','CON'],['Combate','Aparar','FOR','DES'],['Combate','Desviar','PER','DES'],['Combate','Precisão','DES','PER'],['Combate','Liberação','ESP','CON']],
adv:{
CON:[['Dama de Aço',['Luta no Chão','Pede pra Sair','Garra de Caranguejo']],['Olímpico',['Quarterback','Corpo Mole','Hiper Denso']],['Nervos de Aço',['Duro de Matar','Calejado','Vaso Ruim']],['Primitivo',['Instinto de Sobrevivência','Peso Pesado','Segurar']]],
FOR:[['Ataque!!',['Ataque Poderoso','Ataque Imprudente','Ataque Devastador']],['Quebra Queixo',['Mestre da Quebra','Onda de Choque','Trinca Ferro']],['Brutamonte',['Mestre do Agarrão','Fomento Corporal','Bárbaro']],['Bala de Canhão',['Ação Explosiva','Pancadão','Reflexo Reativo']]],
DES:[['Hiperativo',['Ação em Movimento','Pula Catraca','Proativo']],['Atrás de Você',['Agora Você Me Vê…','Rolamento Tático','Esquiva Fabulosa']],['Nocaute',['Calcanhar de Aquiles','Ataque Dominó','Desarmar Aprimorado']],['Nas Nuvens',['Pés de Dançarino','Melhor Prevenir','Movimento Sincronizado']]],
INT:[['Favoritismo',['Ambiente Favorito','Inimigo Favorito','Arma Favorita']],['Talento Natural',['É Jeito','Vivendo e Aprendendo','Memória Fotográfica']],['Espertalhão',['Eureka!','Pelos Meus Cálculos...','Plano B']],['Gênio',['Frio e Calculista','Rotineiro','Pronto Socorro']]],
PER:[['Suricato',['Sentido Superior','Pensa Rápido','Paranoico']],['Analista',['Ponto Crítico','Mestre da Cópia','Duelista']],['Predador',['Ouvido de Morcego','Olhos Afiados','Olhos de Falcão']],['Albatroz',['Mirar','Vira-Lata','Explorador']]],
CAR:[['Superficial',['Atraente','Assustar','Fascinar']],['Babaca',['Zombar','Protagonista','Ele é Mais Apetitoso']],['Empático',['Ombro Amigo','O que os Olhos Veem','O Coração Sente']],['Molejo',['Coreografia','Malandro','Temos um Acordo?']]],
ESP:[['Espiritualista',['Canalização Forçada','Manipulação Centrada','Fluxo Espiritual']],['Corpóreo',['Espírito de Luta','Instinto Primal','Corpo Impuro']],['Dominador',['Pressão Espiritual','Suprimir Presença','Alma Inabalável']],['Anormal',['Mente Vazia','Máximo Potencial','Talento Nato']]],
SORTE:[['Roda da Fortuna',['JACKPOT!','Cara ou Coroa?','Golpe de Sorte']],['Mão de Vaca',['Deixo pra Próxima','Auto Sabotagem','Guardar para Mais Tarde']],['É Agora',['Tudo ou Nada','Por Pouco','Nem Fudendo']],['Pé Frio',['Azarão','Palhaço','Deixa Comigo!']]]}
};
