const Q={
attrs:[['CON','Constituição'],['FOR','Força'],['DES','Destreza'],['INT','Intelecto'],['PER','Percepção'],['CAR','Carisma'],['ESP','Espírito']],
mastery:{
CON:[[4,'Casca Grossa','Desconfortos físicos momentâneos, como dor leve ou náusea, não atrapalham seu desempenho.'],[8,'Corpo Resiliente','Desconfortos físicos persistentes, como frio, calor, dor ou o início da exaustão, não atrapalham seu desempenho.'],[12,'Ritmo Constante','Efeitos físicos negativos levam mais tempo para se manifestar por completo em você.'],[16,'Persistência Física','Mesmo em estado crítico, você continua funcional enquanto ainda houver uma condição física mínima para agir.']],
FOR:[[4,'Pulso Firme','Testes que envolvem força explosiva ficam mais fáceis para você. Isso não altera a DT de acerto de ataques.'],[8,'Fibrado','Você não sofre penalidades por carga comum, esforço físico cotidiano ou uso prolongado do corpo.'],[12,'Bodylifter','Ações físicas simples, como empurrar, levantar, segurar ou arrombar estruturas frágeis, não exigem teste quando não houver oposição real ou risco.'],[16,'Muralha','Quando presença corporal importa, o mestre deve considerar você uma pressão física constante para ocupar espaço, bloquear passagem ou impor contato.']],
DES:[[4,'Mãos Ágeis','Ações motoras simples, como sacar, pegar ou lançar um objeto, raramente exigem teste.'],[8,'Coordenação Básica','Ações motoras comuns, como equilíbrio simples, manuseio rápido e movimentos cotidianos, raramente exigem teste.'],[12,'Movimento Adaptável','Ambientes irregulares ou apertados raramente colocam você em desvantagem narrativa imediata.'],[16,'Fluidez Natural','Sua movimentação raramente chama atenção negativa ou cria uma abertura óbvia por si só.']],
INT:[[4,'CDF','Você possui conhecimento geral de ciências básicas. Investigações e análises que dependam apenas desse conhecimento não exigem teste.'],[8,'Nerdola','Você possui conhecimento geral de ciências intermediárias. Investigações e análises que dependam desse nível de conhecimento não exigem teste.'],[12,'Analista de Campo','Uma vez por cena, quando houver algo que possa ser deduzido por ordem, padrão ou lógica, você pode encontrar uma vulnerabilidade em um inimigo ou no ambiente sem teste.'],[16,'Mestre da Gambiarra','Construções improvisadas e mecânica de nível intermediário não exigem rolagem quando você tiver materiais e tempo compatíveis.']],
PER:[[4,'Bala na Agulha','Testes básicos de precisão e iniciativa recebem margem de acerto 2.'],[8,'Atenção Ativa','Detalhes evidentes do ambiente raramente passam despercebidos por você.'],[12,'Leitura do Ambiente','Ao entrar em uma cena nova, o mestre fornece informações contextuais extras, como movimentos, padrões ou algo fora do lugar, mesmo sem um teste específico.'],[16,'Sexto Sentido','Você se torna imune às penalidades de “desatento” e “surpreso”.']],
CAR:[[4,'Charlatão','Você não precisa de teste para perceber a intenção de alguém despreparado.'],[8,'Boa Pinta','Ao mentir para alguém com poucas informações ou fora de contexto, normalmente não é necessária rolagem.'],[12,'Popular','Em interações para conseguir informações, dados simples não exigem rolagem. Informações mais guardadas ficam com ND menor.'],[16,'Popstar','Ao fascinar ou cativar alvos mundanos, normalmente não é necessária rolagem.']],
ESP:[[4,'Místico','Você tem facilidade para identificar o tipo de presença paranormal de um ser, objeto ou manifestação específica.'],[8,'Sensitivo','Fenômenos espirituais ou energéticos raramente passam completamente despercebidos por você.'],[12,'Esotérico','Manifestações ocultas simples e intermediárias não exigem teste para serem compreendidas.'],[16,'Transcendente','Sua existência interfere no equilíbrio espiritual ao redor, dificultando tentativas inimigas de interferir na sua mente.']]},
skills:[
['Físicas','Fortitude','CON'],['Físicas','Movimento','DES'],['Físicas','Postura','CON'],['Físicas','Agilidade','DES'],['Físicas','Potência','FOR'],['Físicas','Visão','PER'],['Físicas','Audição','PER'],['Físicas','Intimidação','CON'],
['Mentais','Investigação','INT'],['Mentais','Ocultismo','INT'],['Mentais','Astúcia','INT'],['Mentais','Atração','CAR'],['Mentais','Observação','PER'],['Mentais','Ciências','INT'],['Mentais','Cuidados','INT'],['Mentais','Pilotar','DES'],['Mentais','Sobrevivência','INT'],['Mentais','Persuasão','CAR'],['Mentais','Inspiração','CAR'],['Mentais','Presença','ESP'],['Mentais','Compostura','ESP'],['Mentais','Linguagens','INT'],
['Combate','Técnica','DES','INT'],['Combate','Briga','FOR','CON'],['Combate','Aparar','FOR','DES'],['Combate','Desviar','PER','DES'],['Combate','Precisão','DES','PER'],['Combate','Liberação','ESP','CON']],
adv:{
CON:[['Dama de Aço',['Luta no Chão','Pede pra Sair','Garra de Caranguejo']],['Olímpico',['Quarterback','Corpo Mole','Hiper Denso']],['Nervos de Aço',['Duro de Matar','Calejado','Vaso Ruim']],['Primitivo',['Instinto de Sobrevivência','Peso Pesado','Segurar']]],
FOR:[['Ataque!!',['Ataque Poderoso','Ataque Imprudente','Ataque Devastador']],['Quebra Queixo',['Mestre da Quebra','Onda de Choque','Trinca Ferro']],['Brutamonte',['Mestre do Agarrão','Fomento Corporal','Bárbaro']],['Bala de Canhão',['Ação Explosiva','Pancadão','Reflexo Reativo']]],
DES:[['Hiperativo',['Ação em Movimento','Pula Catraca','Proativo']],['Atrás de Você',['Agora Você Me Vê…','Rolamento Tático','Esquiva Fabulosa']],['Nocaute',['Calcanhar de Aquiles','Ataque Dominó','Desarmar Aprimorado']],['Nas Nuvens',['Pés de Dançarino','Melhor Prevenir','Movimento Sincronizado']]],
INT:[['Favoritismo',['Ambiente Favorito','Inimigo Favorito','Arma Favorita']],['Talento Natural',['É Jeito','Vivendo e Aprendendo','Memória Fotográfica']],['Espertalhão',['Eureka!','Pelos Meus Cálculos...','Plano B']],['Gênio',['Frio e Calculista','Rotineiro','Pronto Socorro']]],
PER:[['Suricato',['Sentido Superior','Pensa Rápido','Paranoico']],['Analista',['Ponto Crítico','Mestre da Cópia','Duelista']],['Predador',['Ouvido de Morcego','Olhos Afiados','Olhos de Falcão']],['Albatroz',['Mirar','Vira-Lata','Explorador']]],
CAR:[['Superficial',['Atraente','Assustar','Fascinar']],['Babaca',['Zombar','Protagonista','Ele é Mais Apetitoso']],['Empático',['Ombro Amigo','O que os Olhos Veem','O Coração Sente']],['Molejo',['Coreografia','Malandro','Temos um Acordo?']]],
ESP:[['Espiritualista',['Canalização Forçada','Manipulação Centrada','Fluxo Espiritual']],['Corpóreo',['Espírito de Luta','Instinto Primal','Corpo Impuro']],['Dominador',['Pressão Espiritual','Suprimir Presença','Alma Inabalável']],['Anormal',['Mente Vazia','Máximo Potencial','Talento Nato']]],
SORTE:[['Roda da Fortuna',['JACKPOT!','Cara ou Coroa?','Golpe de Sorte']],['Mão de Vaca',['Deixo pra Próxima','Auto Sabotagem','Guardar para Mais Tarde']],['É Agora',['Tudo ou Nada','Por Pouco','Nem Fudendo']],['Pé Frio',['Azarão','Palhaço','Deixa Comigo!']]]}
};
